# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
email: drew.johnston13@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Mathematician, Data Scientist, and Machine Learning Enthusiast. Here I display my experience, personal projects, and resume for your viewing pleasure.
github_username: drewjohnston13
minimal_mistakes_skin: "default"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Drew Johnston"
  avatar : "/assets/images/profile.jpg"
  bio    : "Passionate Mathematician, Data Scientist, and Machine Learning Enthusiast."
  links:
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://"
    - label: "Provo, Utah"
      icon: "fa fa-map-marker"
      url: "https://www.google.com/maps/place/Provo,+UT/@40.2572504,-111.7789927,11z/data=!3m1!4b1!4m5!3m4!1s0x874d9271930bf1bf:0x1d90f12600b556ef!8m2!3d40.2338438!4d-111.6585337"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/drewjohnston13"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/drewjohnston13/"
    
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/drewjohnston13"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/drewjohnston13/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

project_archive:
  type: liquid
  path: /projects/
paper_archive:
  type: liquid
  path: /papers/
